### ISSUE TITLE
Extents.extents ?

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Extents.jl#9]
What are peoples thoughts about adding

function extents(;X , Y)
    ex = Extents(X=extrema(X), Y = extrema(Y))
    return ex
end

**Comment by rafaqz** [comment]
What are X and Y? Arrays/ranges?

One problem is the extent is often not yhe stary/end of a range, because the last step needs to be added for intervals.

**Comment by rafaqz** [comment]
How would you handle it with multiple dispatch? A Vector can represent intervals or points, but have a different extent.

I dont really understand what you are proposing.

**Comment by alex-s-gardner** [comment]
OK, to me it seemed strait forward. If you have a dataset and you want to construct an `Extent` you could simply pass `Extents.extents` the coordinates or a range. I do this every time a create a new Tyler plot or want to check if two datasets have overlapping bounding boxes.

**Comment by rafaqz** [comment]
But what is the range

**Comment by rafaqz** [comment]
But what is your particular range _from_?

**Comment by rafaqz** [comment]
Im trying to tease out the problem that a range can represent two (even four) different extents, not one. And we dont know which.

We can use the start and end points as a point to point extent, of course. So `(first(r), last(r))`. But ranges have a step size, so we can also calculate the _interval_ extent `(first(r), last(r)+step(r))` if the values are for the starts of each pixel.

Its very common in raster or image data that the range of pixel point locations represent the start or center of intervals. When ypu pass a range of tick values to a heatmap in Makie, theyre the centers of intervals. So the extent is half a pizel larger on each side. So `(first(r) - step(r)/2, last(r)+step(r)/2).

And if you load a tif with Rasters.jl chances are thats what the lookup ranges mean. When you call `extent` on them this math is done for you because Rasters.jl tracks these things in the wrapper.

**Comment by alex-s-gardner** [comment]
OK, I follow but in my eyes this has already been defined extrema(Range)... if the user is using Range in a way in which the Extents are not defined by Range alone then they would need to explicitly define their Extent ... the function could be defined as:

```
    extents(; X, Y)
Returns the Extent based on the minimum and maximum values of inputs X and Y
```

**Comment by alex-s-gardner** [comment]
Pixel centers vs. pixel edges is an issue that has plagued raster data for decades... I wish we had only opted for a single convention

**Comment by rafaqz** [comment]
I think people van jist call `X=extrema(xs)` themselves tho if they mean that? 

I prefer that to the swathes of inevetably wrong Makie plots for the next decade that people will bug me about.

**Comment by alex-s-gardner** [comment]
Fair point.
